### ISSUE TITLE
ビルドができなくて困ってます

### ISSUE THREAD

**Issue by KITTY1998** [techlabxe/d3d12_book_1#1]
==========================
=問題のコード
==========================
void C_DirectX12Base::Initialize(HWND hWnd)
{
	HRESULT hr;
	UINT dxgiFlags = 0;

#if defined(_DEBUG)
	ComPtr<ID3D12Debug> debug;

	if (SUCCEEDED(D3D12GetDebugInterface(IID_PPV_ARGS(&debug))))
	{
		debug->EnableDebugLayer();
		dxgiFlags |= DXGI_CREATE_FACTORY_DEBUG;

#if 0 // GBV を有効化する場合.
		ComPtr<ID3D12Debug3> l_debug3;
		debug.As(&l_debug3);
		if (l_debug3)
		{
			l_debug3->SetEnableGPUBasedValidation(true);
		}
#endif
	}

#endif

	ComPtr<IDXGIFactory3> factory;
	hr = CreateDXGIFactory2(dxgiFlags, IID_PPV_ARGS(&factory));

	if (FAILED(hr))
	{
		throw std::runtime_error("CreateDXGIFactory2 failed.");
	}

	//ハードウェアアダプタの検索
	ComPtr<IDXGIAdapter1> useAdapter;
	{
		UINT adapterIndex{};
		ComPtr<IDXGIAdapter1> adapter;

		while (DXGI_ERROR_NOT_FOUND != factory->EnumAdapters1(adapterIndex, &adapter))
		{
			DXGI_ADAPTER_DESC1 desc1{};
			adapter->GetDesc1(&desc1);
			++adapterIndex;
			if (desc1.Flags & DXGI_ADAPTER_FLAG_SOFTWARE)
				continue;

			//D3D12は使用可能か
			hr = D3D12CreateDevice(adapter.Get(), D3D_FEATURE_LEVEL_11_0,                __uuidof(ID3D12Device), nullptr);   ←  ここの部分がエラー箇所(ここで止まる)

			if (SUCCEEDED(hr)) 
				break;
		}

		//使用するアダプター
		adapter.As(&useAdapter);
	}

	hr = D3D12CreateDevice(useAdapter.Get(),
		D3D_FEATURE_LEVEL_11_0,
		IID_PPV_ARGS(&m_device));
ーー以下省略

==========================
=エラーコード
==========================
0x00007FF87C8D60F0 (K7CrvrEx64.dll) で例外がスローされました (DirectX12.exe 内): 0xC0000005: 場所 0x00007FF7B14CD000 の読み取り中にアクセス違反が発生しました

アクセス違反なのでポインタの問題かと思ったんですが、特定までいけませんでした。

==========================
=使用環境
==========================
OS:Windows10 Home (Ver.1903)
グラボ: Gforce GTX 1060
メモリ:16GB
VisualStudio 2017 15.9.17

==========================
=備考
==========================
Dxdiagで確認したらDirectXのバージョンは12になってました。
ほかの方が作成したサンプルでは動いたのでDirectX12が使用できないということはまいはずです。
https://github.com/microsoft/DirectX-Graphics-Samples.git

**Comment by techlabxe** [comment]
こちら ( https://teratail.com/questions/219440 ) のほうでも質問されているようなので、両者を総合して確認させてもらいました。またビルドが出来ないと言うのではなくて、実行するとエラーになるという質問として受け取っております。

terateil のほうのソースコードでは、while 処理ブロックが次の内容で終わっており、末尾の戻り値のチェックが抜けているようです。この部分を確認してみてください。
```
//D3D12は使用可能か
l_hr = D3D12CreateDevice(....
// 本来なら以下のコードもあるはず
//if (SUCCEEDED(hr))
//        break;
```

次に問題を起こしているDLLが、ウィルスセキュリティZEROのもののようです。
可能であれば、プログラムを実行するまえに無効化して、実行出来るかを確認してみてください。


### 他の回避方法など
"// ハードウェアアダプタの検索 " でハードウェアアダプタを検索して処理していますが、
これは、参考に上げられているコードで言えば `GetHardwareAdapter` 関数と同じ処理になります。
このコードで問題が出ないのであれば、こちらのコードを参考にしながら当てはめてもらうか、両者を比較して差異を見つけるなど、が考えられます。

```
void DXSample::GetHardwareAdapter(IDXGIFactory2* pFactory, IDXGIAdapter1** ppAdapter)
{
    ComPtr<IDXGIAdapter1> adapter;
    *ppAdapter = nullptr;

    for (UINT adapterIndex = 0; DXGI_ERROR_NOT_FOUND != pFactory->EnumAdapters1(adapterIndex, &adapter); ++adapterIndex)
    {
        DXGI_ADAPTER_DESC1 desc;
        adapter->GetDesc1(&desc);

        if (desc.Flags & DXGI_ADAPTER_FLAG_SOFTWARE)
        {
            // Don't select the Basic Render Driver adapter.
            // If you want a software adapter, pass in "/warp" on the command line.
            continue;
        }

        // Check to see if the adapter supports Direct3D 12, but don't create the
        // actual device yet.
        if (SUCCEEDED(D3D12CreateDevice(adapter.Get(), D3D_FEATURE_LEVEL_11_0, _uuidof(ID3D12Device), nullptr)))
        {
            break;
        }
    }

    *ppAdapter = adapter.Detach();
}
```

あとは、ハードウェアアダプタ検索をいったん無効化して、後の処理の `D3D12CreateDevice` でデフォルトのデバイスで処理させるように対処するのもありかと思います。

```
// デフォルトデバイスを選ばせるために nullptr
hr = D3D12CreateDevice(nullptr, D3D_FEATURE_LEVEL_11_0, IID_PPV_ARGS(&m_device));
```

**Comment by KITTY1998** [comment]
ウイルスセキュリティZeroの問題だったようです。
自分の調べが甘く今回は申し訳なかったです。
親切なご対応ありがとうございます。

**Comment by techlabxe** [comment]
ウィルスセキュリティ ZERO を無効化でうまくいきましたか！
他のサンプルで動いた、という点で不思議な点もありますが、ひとまずはよかったです。
