### ISSUE TITLE
PSOの生成で失敗する

### ISSUE THREAD

**Issue by terraritto** [techlabxe/d3d12_book_1#3]
# コード部分

	// *----- make Pipeline State Object(PSO) -----*
	D3D12_GRAPHICS_PIPELINE_STATE_DESC psoDesc{};
	// set shader
	psoDesc.VS = CD3DX12_SHADER_BYTECODE(mVs.Get());
	psoDesc.PS = CD3DX12_SHADER_BYTECODE(mPs.Get());
	// set blend state
	psoDesc.BlendState = CD3DX12_BLEND_DESC(D3D12_DEFAULT);

	// set rasterriser state
	psoDesc.RasterizerState = CD3DX12_RASTERIZER_DESC(D3D12_DEFAULT);
	// set render target
	psoDesc.NumRenderTargets = 1;
	psoDesc.RTVFormats[0] = DXGI_FORMAT_R8G8B8A8_UNORM;
	// set depth buffer
	psoDesc.DSVFormat = DXGI_FORMAT_D32_FLOAT;
	psoDesc.InputLayout = { inputElementDesc, _countof(inputElementDesc) };
	psoDesc.DepthStencilState = CD3DX12_DEPTH_STENCIL_DESC(D3D12_DEFAULT);
	// set root signature
	psoDesc.pRootSignature = mRootSignature.Get();
	psoDesc.PrimitiveTopologyType = D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE;
	// set multi-sample
	psoDesc.SampleDesc = { 1,0 };
	psoDesc.SampleMask = UINT_MAX;

	hr = mDevice->CreateGraphicsPipelineState(&psoDesc, IID_PPV_ARGS(&mPipeline));

	if (FAILED(hr))
	{
		throw std::runtime_error("CreateGraphicsPipelineState is failed");
	}

# エラー内容
0x00007FFCD968A839 で例外がスローされました (dxsample.exe 内): Microsoft C++ の例外: _com_error (メモリの場所 0x0000009B8BCFCA50)。
0x00007FFCD968A839 で例外がスローされました (dxsample.exe 内): Microsoft C++ の例外: std::runtime_error (メモリの場所 0x0000009B8BCFEE08)。
dxsample.exe によってブレークポイントが発生しました。

CreateGraphicsPipelineState is failed
HRESULT:  E_INVALIDARG One or more arguments are invalid.

# 環境
OS: Windows10 1903
device: NVIDIA GeForce GTX1080
Visual Studio: 2019 ver 16.4.5

# 備考
HRESULTの内容を見る限り何かしら足りない時に流れるエラーだということまではわかりました。
しかし、D3D12_GRAPHICS_PIPELINE_STATE_DESCの中身をブレイクポイントを立ててみた感じ何も渡し忘れたデータが存在しておらず、原因が分からず質問させていただきました。
現在手元に「DirectX12の魔導書」という書籍も存在し、こちらにはルートシグニチャが足りない時に出るエラーと書いてありましたがルートシグニチャもしっかりと入れてありました。
そのため何かしらの入力ミスなども疑い、完全にコピーしたコードを実行してみましたが、同じエラーが起こってしまいどうも手詰まりの状態です。  
何か対応策があれば教えていただければ幸いです。

**Comment by techlabxe** [comment]
全ての情報が詰まっているようですと、悩ましいですね。
DirectX12 Programming Vol.1 第7章 シェーダーの基礎の部分に重要な記載がありまして、
依存関係節について確認されてみるのがよいかなと思います。
（シェーダーの基礎と章題を付けてしまったせいで、読み飛ばされるケースも多く...）

もし fxc を使ってのシェーダーコンパイルを行っている場合にはこの限りではないので、別の要因かと思われます。
（DirectX12 の魔道書のほうでは、こちらの fxc / D3DCompiler を使うタイプで説明されています。魔道書のサンプルプログラムが実行出来る場合には、やはり fxc vs Dxc の差であろうと考えられます）

**Comment by terraritto** [comment]
シェーダーの部分、一応読んでいましたがもう一度確認させていただきました。
その上で依存関係を見てみた感じ何も問題なさそうでした......
一応Dxc,fxcを試すためにDirectX12の魔導書とDirectX12 Programming vol.1の両方のサンプルを試してみましたが、どちらもまた同じエラーが出ている状態です。

**Comment by techlabxe** [comment]
fxc / dxc どちらでもNGということは、環境に対して何か問題があるのかもしれませんね。
DirectX12 のサンプルを、 **他の環境でビルドしてもらったもの** が、お使いの環境で実行出来る場合、開発環境に課題があると考えられます。
他の環境で実行出来るものが同じようにクラッシュするのであれば、そのPC自体に課題があるのかと考えられます。

開発環境に課題があると判明した場合、 Windows SDK の更新・再インストール等で解決することがあるようです。Windows SDK のバージョン（かミスマッチか）によって、 CreateGraphicsPipelineStateで失敗するプログラムが生成されてしまうようです。
検索して調べてみた結果なので手元で確認が取れているわけでなく紹介程度となりますが...。

※ 念のためうまく動かない WindowsSDK のバージョンを見せてもらえたら幸いです。
プロジェクトのプロパティにて、  **Windows SDK バージョン**

**Comment by terraritto** [comment]
上手くいかない Windows SDK のバージョンは10.0.18362.0となっております。
一応再インストールはしてみましたがダメそうです......

**Comment by techlabxe** [comment]
こちらでも同じ SDK バージョンで試してみましたが、問題なく動作しました。

デバッグレイヤーは有効化していますか？
デバッグレイヤーが有効化状態において、他の警告メッセージなどは通知されていなかったでしょうか？

可能であればプログラム一式を zip 等で固めてあげてもらい、こちらでビルド＆実行してみようかと思います。

**Comment by terraritto** [comment]
デバッグレイヤー有効化にしていませんでした......
有効化した結果次のエラーが確認できました。

* D3D12 ERROR: ID3D12Device::CreateInputLayout: Input Signature in bytecode could not be parsed.  Data may be corrupt or in an unrecognizable format. [ STATE_CREATION ERROR #63: CREATEINPUTLAYOUT_UNPARSEABLEINPUTSIGNATURE]
* D3D12 ERROR: ID3D12Device::CreateVertexShader: Vertex Shader is corrupt or in an unrecognized format. [ STATE_CREATION ERROR #67: CREATEVERTEXSHADER_INVALIDSHADERBYTECODE]
* D3D12 ERROR: ID3D12Device::CreatePixelShader: Pixel Shader is corrupt or in an unrecognized format. [ STATE_CREATION ERROR #93: CREATEPIXELSHADER_INVALIDSHADERBYTECODE]

エラーの内容を見た感じすらりん日記様のDXRの始め方の際のエラーと同じようですが、開発者モードにしているので少し悩んでいる感じです。

一応プログラム一式を一時的に上げておきました、お手数ですがこちらから確認していただけるとありがたいです。

[download](https://www.amazon.co.jp/clouddrive/share/jgNeQbwzGvfE4R9tNQNAFrBZI0zGoo0xJGdJhMMNx)

**Comment by techlabxe** [comment]
添付してもらったサンプルを手元で実行させてみました。
（いくつか不要なファイルまでがプロジェクトに追加されているようだったのでそのあたりは修正しましたが）。

結果はこちらの環境では正常に動作しました。
ですので、C++ プログラムとしては間違いはないのではないか、と考えられます。

デバッグレイヤーのエラーメッセージを見る限り、
シェーダーのコンパイルした結果のバイナリデータが不正なように見えます。
`mVs`, `mPs`  変数に書き込まれているデータは正常かどうかを見るところからだと思います。
あとグラフィックスドライバのバージョンはどうでしょうか？現在のお使いのバージョンは？
もし古いようなら、こちらを更新するのもオススメしておきます。

**Comment by terraritto** [comment]
すいませんすべて解決しました......!!
Debugフォルダ内の.exeと同じ階層に.dll関連を試しに放り込んでみたら急に表示されました
前回の依存関係のところでは別のDebugファイルに放り込んでいたようで、その影響でエラーが起こっていたようです......
長い間サンプルまで実行させるなど手間をかけさせて本当に何から何まで本当に申し訳ございません、これでひとまず本のほうも読み進められそうです！

**Comment by techlabxe** [comment]
まずは解決したようでなによりです！
原因としてはDLLの不一致か何かだったということなんでしょうね。
